version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: 
          name: Docker shit
          command: | 
            apt-get update -y
            apt-get install -y sudo
            apt-get install -y software-properties-common
      - run: 
          name: Run Installation script
          command: bash scripts/circleci.sh
